document.addEventListener("DOMContentLoaded",()=>{const q=s=>document.querySelector(s);const out=q("#result");
function daysBetween(a,b){const x=new Date(a),y=new Date(b);return Math.round(Math.abs(y-x)/86400000)}
const t=document.body.dataset.tool;
if(t==="age"){q("#calc").onclick=()=>{const dob=new Date(q("#dob").value),as=new Date(q("#asof").value||new Date());if(!q("#dob").value)return;let years=as.getFullYear()-dob.getFullYear(),months=as.getMonth()-dob.getMonth(),days=as.getDate()-dob.getDate();if(days<0){months--;days+=new Date(as.getFullYear(),as.getMonth(),0).getDate()}if(months<0){years--;months+=12}const total=daysBetween(q("#dob").value,as.toISOString().slice(0,10));out.innerHTML=`<strong>${years} years, ${months} months, ${days} days</strong><br><span class="hint">Approximately ${total.toLocaleString()} days old.</span>`}};
if(t==="percentage"){q("#calc").onclick=()=>{const a=+q("#a").value,b=+q("#b").value;out.innerHTML=isFinite(a)&&isFinite(b)?`<strong>${(a*b/100).toLocaleString()}</strong><br>${b}% of ${a} = ${(a*b/100).toLocaleString()}`:"Enter valid numbers."}};
if(t==="date"){q("#calc").onclick=()=>{if(!q("#a").value||!q("#b").value)return;const d=daysBetween(q("#a").value,q("#b").value);out.innerHTML=`<strong>${d.toLocaleString()} days</strong><br>That's approximately ${(d/7).toFixed(1)} weeks or ${(d/30.4375).toFixed(1)} months.`}};
if(t==="duration"){q("#calc").onclick=()=>{const s=q("#start").value,e=q("#end").value;if(!s||!e)return;let [sh,sm]=s.split(":").map(Number),[eh,em]=e.split(":").map(Number);let m=eh*60+em-(sh*60+sm);if(m<0)m+=1440;out.innerHTML=`<strong>${Math.floor(m/60)}h ${m%60}m</strong><br>${m.toLocaleString()} minutes`}};
if(t==="text"){const area=q("#text");const update=()=>{const v=area.value.trim(),words=v?v.split(/\s+/).length:0,chars=area.value.length; q("#words").textContent=words;q("#chars").textContent=chars};area.oninput=update;update()}
if(t==="resize"){q("#image").onchange=()=>{const f=q("#image").files[0];if(!f)return;const img=new Image();img.onload=()=>{q("#orig").textContent=`${img.width} × ${img.height}px`;q("#width").value=img.width;q("#height").value=img.height};img.src=URL.createObjectURL(f)};q("#download").onclick=()=>{const f=q("#image").files[0];if(!f)return;const img=new Image();img.onload=()=>{const c=document.createElement("canvas"),w=+q("#width").value,h=+q("#height").value;c.width=w;c.height=h;c.getContext("2d").drawImage(img,0,0,w,h);c.toBlob(b=>{const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="resized-image.png";a.click()})};img.src=URL.createObjectURL(f)}}
if(t==="compress"){q("#image").onchange=()=>{const f=q("#image").files[0];if(f)q("#size").textContent=(f.size/1024).toFixed(1)+" KB"};q("#download").onclick=()=>{const f=q("#image").files[0];if(!f)return;const img=new Image();img.onload=()=>{const c=document.createElement("canvas");c.width=img.width;c.height=img.height;c.getContext("2d").drawImage(img,0,0);c.toBlob(b=>{const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="compressed-image.jpg";a.click()},"image/jpeg",+q("#quality").value/100)};img.src=URL.createObjectURL(f)}}
if(t==="qr"){q("#calc").onclick=()=>{const text=encodeURIComponent(q("#text").value.trim());if(!text)return;q("#qr").innerHTML=`<img alt="Generated QR code" src="https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${text}">`}};
if(t==="wifi"){q("#calc").onclick=()=>{const ss=q("#ssid").value,pass=q("#pass").value,sec=q("#security").value;const data=`WIFI:T:${sec};S:${ss};P:${pass};;`;q("#qr").innerHTML=`<img alt="WiFi QR code" src="https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(data)}">`}};
});
