document.addEventListener("DOMContentLoaded",()=>{const q=s=>document.querySelector(s),out=q("#result"),today=new Date().toISOString().slice(0,10),asof=q("#asof");if(asof&&!asof.value)asof.value=today;function daysBetween(a,b){return Math.round(Math.abs(new Date(b)-new Date(a))/86400000)}const t=document.body.dataset.tool;
if(t==="age")q("#calc").onclick=()=>{const dob=q("#dob").value,as=q("#asof").value;if(!dob)return;if(new Date(dob)>new Date(as)){out.textContent="Date of birth must be before the calculation date.";return}let d=new Date(as),b=new Date(dob),y=d.getFullYear()-b.getFullYear(),m=d.getMonth()-b.getMonth(),day=d.getDate()-b.getDate();if(day<0){m--;day+=new Date(d.getFullYear(),d.getMonth(),0).getDate()}if(m<0){y--;m+=12}out.innerHTML=`<strong>${y} years, ${m} months, ${day} days</strong><br><span class="hint">Approximately ${daysBetween(dob,as).toLocaleString()} days.</span>`};
if(t==="percentage")q("#calc").onclick=()=>{const a=+q("#a").value,b=+q("#b").value;out.innerHTML=isFinite(a)&&isFinite(b)?`<strong>${(a*b/100).toLocaleString()}</strong><br>${b}% of ${a} = ${(a*b/100).toLocaleString()}`:"Enter valid numbers."};
if(t==="date")q("#calc").onclick=()=>{if(!q("#a").value||!q("#b").value)return;const d=daysBetween(q("#a").value,q("#b").value);out.innerHTML=`<strong>${d.toLocaleString()} days</strong><br>Approximately ${(d/7).toFixed(1)} weeks or ${(d/30.4375).toFixed(1)} months.`};
if(t==="duration")q("#calc").onclick=()=>{const s=q("#start").value,e=q("#end").value;if(!s||!e)return;let [sh,sm]=s.split(":").map(Number),[eh,em]=e.split(":").map(Number),m=eh*60+em-sh*60-sm;if(m<0)m+=1440;out.innerHTML=`<strong>${Math.floor(m/60)}h ${m%60}m</strong><br>${m.toLocaleString()} minutes`};
if(t==="text"){const area=q("#text"),update=()=>{const v=area.value.trim();q("#words").textContent=v?v.split(/\s+/).length:0;q("#chars").textContent=area.value.length};area.oninput=update;update()}
if(t==="resize")q("#image").onchange=()=>{const f=q("#image").files[0];if(!f)return;const img=new Image();img.onload=()=>{q("#orig").textContent=`${img.width} × ${img.height}px`;q("#width").value=img.width;q("#height").value=img.height};img.src=URL.createObjectURL(f)};if(t==="resize")q("#download").onclick=()=>{const f=q("#image").files[0];if(!f)return;const img=new Image();img.onload=()=>{const w=+q("#width").value,h=+q("#height").value;if(!w||!h)return;const c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(img,0,0,w,h);c.toBlob(b=>{const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="resized-image.png";a.click()},"image/png")};img.src=URL.createObjectURL(f)};
if(t==="compress")q("#download").onclick=()=>{const f=q("#image").files[0];if(!f)return;const img=new Image();img.onload=()=>{const c=document.createElement("canvas");c.width=img.width;c.height=img.height;c.getContext("2d").drawImage(img,0,0);c.toBlob(b=>{const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="compressed-image.jpg";a.click()},"image/jpeg",+q("#quality").value/100)};img.src=URL.createObjectURL(f)};
if(t==="qr")q("#calc").onclick=()=>{const v=q("#text").value.trim();if(!v)return;q("#qr").innerHTML=`<img alt="Generated QR code" src="https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(v)}"><p class="hint">Uses a third-party QR image service. Avoid sensitive data.</p>`};
if(t==="wifi")q("#calc").onclick=()=>{const data=`WIFI:T:${q("#security").value};S:${q("#ssid").value};P:${q("#pass").value};;`;q("#qr").innerHTML=`<img alt="Generated WiFi QR code" src="https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(data)}"><p class="hint">Uses a third-party QR image service. Avoid sensitive network credentials.</p>`};
});